# Pull request
# These are consistency checks that run on every commit in a PR
name: Pull request
on:
  pull_request:
    branches: ["*"]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          npm install
          npm test

  check-formatting:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Run Prettier
        run: |
          npm install
          npx prettier --check .
